name: Capture Done Taps
permissions:
  contents: write

on:
  schedule:
    - cron: '*/10 * * * *'     # runs every 10 min
  workflow_dispatch:           # manual “Run workflow” button

jobs:
  poll:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - run: pip install requests

      - run: python log_responses.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID:        ${{ secrets.CHAT_ID }}
          GITHUB_TOKEN:   ${{ secrets.GITHUB_TOKEN }}
